name: NatuClans
version: '${project.version}'
main: org.kayteam.natuclans.NatuClans
api-version: 1.13
author: KayTeam
website: https://kayteam.org
depend: [WorldGuard, CombatLogX, PlaceholderAPI]
commands:
  natuclans:
    description: NatuClans main command
  clan:
    description: NatuClans clan main command
  plot:
    description: NatuClans plot main command
permissions:
  natuclans.natuclans:
    children:
      - natuclans.natuclans.cmd.createclan
      - natuclans.natuclans.cmd.deleteclan
      - natuclans.natuclans.cmd.reload
      - natuclans.natuclans.cmd.list
  natuclans.cmd.plot:
    children:
      - natuclans.plot.cmd.home
      - natuclans.plot.cmd.settings
      - natuclans.plot.cmd.members
      - natuclans.plot.cmd.add
      - natuclans.plot.cmd.remove
  natuclans.cmd.clan:
    children:
      - natuclans.clan.cmd.leave
      - natuclans.clan.cmd.spawn
      - natuclans.clan.cmd.setspawn
      - natuclans.clan.cmd.settings
      - natuclans.clan.cmd.commonzonesettings
      - natuclans.clan.cmd.members
      - natuclans.clan.cmd.kick
      - natuclans.clan.cmd.addbuilder
      - natuclans.clan.cmd.builders
      - natuclans.clan.cmd.addmanager
      - natuclans.clan.cmd.managers
      - natuclans.clan.cmd.setowner
      - natuclans.clan.cmd.setdisplayname
  natuclans.plot.flag:
    children:
      - natuclans.plot.flag.blockbreak
      - natuclans.plot.flag.blockplace
      - natuclans.plot.flag.use
      - natuclans.plot.flag.interact
      - natuclans.plot.flag.damageanimals
      - natuclans.plot.flag.pvp
      - natuclans.plot.flag.chestaccess
      - natuclans.plot.flag.itempickup
      - natuclans.plot.flag.itemdrop
      - natuclans.plot.flag.mobspawning
      - natuclans.plot.flag.itemframedestroy
      - natuclans.plot.flag.paintingdestroy
      - natuclans.plot.flag.itemframerotate
  natuclans.admin:
    children:
      - natuclans.clan.cmd
      - natuclans.plot.cmd
      - natuclans.natuclans.cmd
      - natuclans.plot.flag